table _medidas
	lineageTag: 7d300411-7984-4c5a-ac77-0930c2806cc2

	measure Media_Bonus_USD = AVERAGE(fato_skills[bonus_anual_usd])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: a5554092-683c-48fc-a4e9-a3ca6569d009

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Gap_Salarial_Genero_Pct = ```
			
			/* Lógica (KPI 2): Mede a disparidade salarial percentual entre homens e mulheres. 
			   Calcula as duas médias isoladas via CALCULATE e devolve a variação tendo a média masculina como base. */
			VAR SalarioHomens = CALCULATE([Media_Salario_USD], dim_employee[genero] = "Masculino")
			VAR SalarioMulheres = CALCULATE([Media_Salario_USD], dim_employee[genero] = "Feminino")
			
			RETURN
			DIVIDE(
			    ([Media_Salario_Homens] - [Media_Salario_Mulheres]), 
			    [Media_Salario_Homens], 
			    0
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: bac04f1c-1ef8-4f1f-aacc-70437a5f00db

	measure Media_Horas_Extras = AVERAGE(fato_skills[horas_extras_por_mes])
		lineageTag: 75937cf0-ace3-4143-93f7-ce52db36536b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Media_Salario_Homens = ```
			
			CALCULATE(
			    [Media_Salario_USD], 
			    dim_employee[genero] = "Masculino"
			)
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: c0b3fc6d-25a0-48e7-8b48-0b8d56ade01b

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Media_Salario_Mulheres = ```
			
			CALCULATE(
			    [Media_Salario_USD], 
			    dim_employee[genero] = "Feminino"
			)
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: c9f35807-01ff-4f3e-8a33-b711e9e76a0f

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Media_Salario_USD = AVERAGE(fato_skills[salario_anual_usd])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 8873c447-a7fe-4a8f-9e42-90ef4c79432e

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Media_Satisfacao = AVERAGE(fato_skills[pontuacao_satisfacao_trabalho])
		lineageTag: b071d901-408f-4cb1-a0ea-71f76f4c79e9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Pct_Recebem_Equity =
			
			DIVIDE(
			    CALCULATE(COUNT(fato_skills[dim_employee.id_funcionario]), fato_skills[quitado] = 1),
			    [Total_Funcionarios],
			    0
			)
		formatString: 0
		lineageTag: c12ce212-2639-4e97-b9ca-daa4184a7c91

	measure Taxa_Busca_Ativa =
			
			DIVIDE(
			    CALCULATE(COUNT(fato_skills[dim_employee.id_funcionario]), fato_skills[is_actively_looking] = 1),
			    [Total_Funcionarios],
			    0
			)
		formatString: 0
		lineageTag: 58e2e270-8ce5-4710-a2f1-99cc15dd695e

	measure Total_Funcionarios = COUNT(dim_employee[id_funcionario])
		formatString: 0
		lineageTag: 319cfde5-980d-47c7-b39f-ab2636ae9867

	measure Total_Funcionarios_YTD = ```
			
			/* Lógica: Calcula a quantidade acumulada de profissionais desde o primeiro dia do ano atual 
			   (1 de Janeiro) até à data máxima contextualizada pelo relatório. */
			TOTALYTD(
			    [Total_Funcionarios], 
			    dim_calendario[Date]
			)
			```
		formatString: 0
		lineageTag: cbf4f339-c6f0-4bfe-9040-5a195da74baa

	measure Total_Funcionarios_AnoAnterior = ```
			
			/* Lógica: Utiliza a função SAMEPERIODLASTYEAR como modificador temporal para deslocar 
			   o filtro atual exatamente um ano para trás, permitindo comparações históricas. */
			CALCULATE(
			    [Total_Funcionarios], 
			    SAMEPERIODLASTYEAR(dim_calendario[Date])
			)
			```
		formatString: 0
		lineageTag: 2003ec47-5357-4ba9-8f00-7a4f1b48c99a

	measure Crescimento_Salarial_YoY_Pct = ```
			
			/* Lógica: Avalia o crescimento da média salarial ano contra ano (Year-over-Year). 
			   Armazena a média do ano passado numa variável e calcula o crescimento percentual do período atual. */
			VAR MediaAnoAnterior = 
			    CALCULATE(
			        [Media_Salario_USD], 
			        SAMEPERIODLASTYEAR(dim_calendario[Date])
			    )
			
			RETURN
			DIVIDE(
			    ([Media_Salario_USD] - MediaAnoAnterior), 
			    MediaAnoAnterior, 
			    0
			)
			```
		lineageTag: 5f4c9a10-1516-4ed6-ac80-03d9c7b35dd7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Total_Funcionarios_Painel = ```
			
			/* Lógica: Conta o total de funcionários ativos considerando apenas os filtros dos segmentadores visuais.
			   O modificador ALLSELECTED limpa os filtros internos das linhas ou colunas de um gráfico, 
			   sendo ideal para calcular percentuais dinâmicos em relação ao total filtrado pelo utilizador. */
			CALCULATE(
			    [Total_Funcionarios], 
			    ALLSELECTED(dim_employee)
			)
			```
		formatString: 0
		lineageTag: f30274ab-b0e3-47d9-8d48-2d1880d3317f

	measure Indice_Relevancia_Cargo = ```
			
			/* Lógica (KPI 5): Este índice divide a média salarial do cargo atual pela média geral de toda a base. 
			   O modificador ALL é crucial aqui pois força o CALCULATE a ignorar o filtro do cargo na linha, 
			   permitindo descobrir se a função opera acima ou abaixo da média global (1.0). */
			DIVIDE(
			    [Media_Salario_USD], 
			    CALCULATE([Media_Salario_USD], ALL(dim_job)), 
			    0
			)
			```
		lineageTag: ce9e7bb1-819d-4ecf-8aa0-cf2f70f22c8a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition _medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	changedProperty = Name

	annotation PBI_ResultType = Table

